#!/usr/bin/env python3
"""
Downloads latest CS2 offsets from a2x/cs2-dumper and regenerates src/game/offsets.hpp.

Usage:
  python update_offsets.py
"""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path

OFFSETS_URL = "https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/offsets.json"
TARGET = Path("src/game/offsets.hpp")


def _read_json(url: str) -> dict:
    with urllib.request.urlopen(url, timeout=20) as response:
        return json.loads(response.read().decode("utf-8"))


def _hex(v: int) -> str:
    return f"0x{v:X}"


def main() -> None:
    data = _read_json(OFFSETS_URL)
    client = data["client.dll"]

    # Hard requirements from this project.
    values = {
        "dwEntityList": client["dwEntityList"],
        "dwLocalPlayerController": client["dwLocalPlayerController"],
        "dwLocalPlayerPawn": client["dwLocalPlayerPawn"],
        "dwViewMatrix": client["dwViewMatrix"],
        "dwGameEntitySystem": client["dwGameEntitySystem"],
        "dwGlobalVars": client["dwGlobalVars"],
        "m_vecOrigin": 0x88,     # CGameSceneNode::m_vecOrigin
        "m_iHealth": 0x344,
        "m_iTeamNum": 0x3E3,
        "m_lifeState": 0x348,
        "m_pGameSceneNode": 0x328,
        "m_modelState": 0x170,
        "m_hPlayerPawn": 0x80C,
        "m_iShotsFired": 0x22B0,
        "m_pBoneArray": 0x80,    # CModelState + m_pBoneArray
    }

    rendered = f"""#pragma once
#include <cstdint>

namespace offsets {{
    // Auto-generated by update_offsets.py from:
    // {OFFSETS_URL}
    constexpr uintptr_t dwEntityList = {_hex(values["dwEntityList"])};
    constexpr uintptr_t dwLocalPlayerController = {_hex(values["dwLocalPlayerController"])};
    constexpr uintptr_t dwLocalPlayerPawn = {_hex(values["dwLocalPlayerPawn"])};
    constexpr uintptr_t dwViewMatrix = {_hex(values["dwViewMatrix"])};
    constexpr uintptr_t dwGameEntitySystem = {_hex(values["dwGameEntitySystem"])};
    constexpr uintptr_t dwGlobalVars = {_hex(values["dwGlobalVars"])};

    constexpr uintptr_t m_vecOrigin = {_hex(values["m_vecOrigin"])};
    constexpr uintptr_t m_iHealth = {_hex(values["m_iHealth"])};
    constexpr uintptr_t m_iTeamNum = {_hex(values["m_iTeamNum"])};
    constexpr uintptr_t m_lifeState = {_hex(values["m_lifeState"])};
    constexpr uintptr_t m_pGameSceneNode = {_hex(values["m_pGameSceneNode"])};
    constexpr uintptr_t m_modelState = {_hex(values["m_modelState"])};
    constexpr uintptr_t m_hPlayerPawn = {_hex(values["m_hPlayerPawn"])};
    constexpr uintptr_t m_iShotsFired = {_hex(values["m_iShotsFired"])};
    constexpr uintptr_t m_pBoneArray = {_hex(values["m_pBoneArray"])};
}}
"""

    TARGET.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {TARGET}")


if __name__ == "__main__":
    main()
